from fastapi import APIRouter, Request, Response, HTTPException
import os
import httpx
import hmac
import hashlib
import re
import logging
from fastapi.concurrency import run_in_threadpool
from database import SessionLocal
from sqlalchemy.exc import IntegrityError
from models import ProcessedWebhook, Cafe

logger = logging.getLogger(__name__)

META_APP_SECRET = os.getenv("META_APP_SECRET", "dummy_meta_secret")

router = APIRouter()

META_VERIFY_TOKEN = os.getenv("META_VERIFY_TOKEN", "qrate_verify_123")
META_ACCESS_TOKEN = os.getenv("META_ACCESS_TOKEN", "dummy_token_replace_in_prod")
META_PHONE_ID = os.getenv("META_PHONE_ID", "dummy_phone_id")
WABA_PHONE_NUMBER = os.getenv("WABA_PHONE_NUMBER", "919999999999")

@router.get("/config")
def get_whatsapp_config():
    """
    Returns public config required by the frontend (like the WhatsApp bot phone number)
    """
    return {
        "waba_phone_number": WABA_PHONE_NUMBER
    }

@router.get("/webhook")
def verify_webhook(request: Request):
    """
    Required by Meta to verify the webhook endpoint URL during setup.
    """
    mode = request.query_params.get("hub.mode")
    token = request.query_params.get("hub.verify_token")
    challenge = request.query_params.get("hub.challenge")

    if mode == "subscribe" and token == META_VERIFY_TOKEN:
        return Response(content=challenge, media_type="text/plain")
    raise HTTPException(status_code=403, detail="Forbidden")


from routers.auth import create_access_token
from limiter import limiter

FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173")

def _check_webhook_replay(message_id: str) -> bool:
    db = SessionLocal()
    try:
        new_webhook = ProcessedWebhook(message_id=message_id)
        db.add(new_webhook)
        db.commit()
        return False
    except IntegrityError:
        db.rollback()
        return True
    finally:
        db.close()

@router.post("/webhook")
@limiter.limit("100/minute")
async def receive_webhook(request: Request):
    """
    Receives inbound messages and delivery status updates from Meta.
    """
    signature = request.headers.get("x-hub-signature-256")
    body_bytes = await request.body()
    
    if not signature or not signature.startswith("sha256="):
        raise HTTPException(status_code=403, detail="Invalid Meta signature format")
        
    actual_signature = signature.split("sha256=")[1]
    expected_signature = hmac.new(
        META_APP_SECRET.encode("utf-8"),
        body_bytes,
        hashlib.sha256
    ).hexdigest()
    
    if not hmac.compare_digest(expected_signature, actual_signature):
        raise HTTPException(status_code=403, detail="Invalid Meta signature")

    try:
        body = await request.json()

        # Parse inbound WhatsApp messages (payload is heavily nested)
        if body.get("object") == "whatsapp_business_account":
            for entry in body.get("entry", []):
                for change in entry.get("changes", []):
                    value = change.get("value", {})
                    if "messages" not in value:
                        continue
                    for msg in value.get("messages", []):
                        message_id = msg.get("id")
                        if message_id:
                            is_replay = await run_in_threadpool(_check_webhook_replay, message_id)
                            if is_replay:
                                continue

                        phone_number = msg.get("from")
                        text_body = msg.get("text", {}).get("body", "").strip()
                        normalised = text_body.replace(" ", "").lower()

                        # Expect the exact format generated by our QR code deep link:
                        # "RateMyVisit <cafe_id>"  e.g. "ratemyvisit 42"
                        match = re.search(r'ratemyvisit(\d+)', normalised)
                        if not match:
                            # Unrecognised message — send a friendly help reply
                            await send_whatsapp_text(
                                to_phone=phone_number,
                                text_message="Hi! Please scan the QR code at the cafe counter to leave feedback and claim your reward."
                            )
                            continue

                        cafe_id = int(match.group(1))

                        # Validate the cafe exists and is active before issuing a token
                        def _lookup_cafe(cid: int):
                            db = SessionLocal()
                            try:
                                return db.query(Cafe).filter(
                                    Cafe.id == cid,
                                    Cafe.subscription_status.in_(["active", "trial"])
                                ).first()
                            finally:
                                db.close()

                        cafe = await run_in_threadpool(_lookup_cafe, cafe_id)
                        if not cafe:
                            await send_whatsapp_text(
                                to_phone=phone_number,
                                text_message="Sorry, we couldn't find that cafe. Please re-scan the QR code."
                            )
                            continue

                        # Issue a scoped customer token and send the feedback link
                        token_data = {
                            "sub": phone_number,
                            "cafe_id": cafe_id,
                            "iss": "qrate-customer",
                            "aud": f"cafe-{cafe_id}",
                        }
                        token = create_access_token(token_data)
                        feedback_url = f"{FRONTEND_URL}/feedback?token={token}"

                        # Service conversation reply (free tier, no template approval needed)
                        await send_whatsapp_text(
                            to_phone=phone_number,
                            text_message=f"Thank you for visiting {cafe.name}! Leave your feedback and claim your reward here: {feedback_url}"
                        )

        return {"status": "ok"}
    except Exception as e:
        logger.error(f"WhatsApp webhook error: {e}", exc_info=True)
        return {"status": "error"}

async def send_whatsapp_text(to_phone: str, text_message: str):
    """
    Fires a raw text message to the customer. 
    This ONLY works if they messaged us within the last 24 hours (Service Conversation).
    """
    url = f"https://graph.facebook.com/v18.0/{META_PHONE_ID}/messages"
    headers = {
        "Authorization": f"Bearer {META_ACCESS_TOKEN}",
        "Content-Type": "application/json"
    }
    
    if len(to_phone) == 10:
        to_phone = "91" + to_phone

    payload = {
        "messaging_product": "whatsapp",
        "to": to_phone,
        "type": "text",
        "text": {
            "preview_url": True,
            "body": text_message
        }
    }

    if META_ACCESS_TOKEN == "dummy_token_replace_in_prod":
        logging.info(f"DUMMY MODE: Simulating WhatsApp Text to {to_phone}: {text_message}")
        return {"simulated": True}

    async with httpx.AsyncClient() as client:
        try:
            resp = await client.post(url, headers=headers, json=payload)
            resp.raise_for_status()
            return resp.json()
        except Exception as e:
            logging.error(f"Failed to send text: {e}")
            return {"error": str(e)}

async def send_whatsapp_template(to_phone: str, template_name: str, components: list):
    """
    Fires a business-initiated template message to the customer (costs ~$0.01 / ~₹0.80).
    Requires the template to be pre-approved in Meta Business Manager.
    """
    url = f"https://graph.facebook.com/v18.0/{META_PHONE_ID}/messages"
    headers = {
        "Authorization": f"Bearer {META_ACCESS_TOKEN}",
        "Content-Type": "application/json"
    }
    
    # Normalize India phone number if needed
    if len(to_phone) == 10:
        to_phone = "91" + to_phone

    payload = {
        "messaging_product": "whatsapp",
        "to": to_phone,
        "type": "template",
        "template": {
            "name": template_name,
            "language": {
                "code": "en_US" # or en, based on your template
            },
            "components": components
        }
    }

    # Don't actually hit the Meta API if we are just testing with dummy tokens
    if META_ACCESS_TOKEN == "dummy_token_replace_in_prod":
        logging.info(f"DUMMY MODE: Simulating WhatsApp Template '{template_name}' sent to {to_phone}")
        return {"messaging_product": "whatsapp", "simulated": True}

    async with httpx.AsyncClient() as client:
        try:
            resp = await client.post(url, headers=headers, json=payload)
            resp.raise_for_status()
            return resp.json()
        except httpx.HTTPStatusError as e:
            logging.error(f"Meta API Error: {e.response.text}")
            return {"error": e.response.text}
        except Exception as e:
            logging.error(f"Request Error: {e}")
            return {"error": str(e)}
