"""add_cafe_metadata_retry

Revision ID: 8c90a52a1950
Revises: 98054c65afeb
Create Date: 2026-01-23 14:15:01.359259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c90a52a1950'
down_revision: Union[str, Sequence[str], None] = '98054c65afeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cafes', sa.Column('reward_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cafes', 'reward_text')
    # ### end Alembic commands ###
