"""Add marketing opt_in and credits

Revision ID: 8d9968451bf5
Revises: f9f97cae53ab
Create Date: 2026-05-07 22:25:26.063408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d9968451bf5'
down_revision: Union[str, Sequence[str], None] = 'f9f97cae53ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cafes', sa.Column('marketing_credits', sa.Integer(), server_default='0', nullable=False))
    op.add_column('feedbacks', sa.Column('marketing_opt_in', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'marketing_opt_in')
    op.drop_column('cafes', 'marketing_credits')
    # ### end Alembic commands ###
