"""initial_schema_with_auth

Revision ID: 9adfba05249b
Revises: 
Create Date: 2026-05-17 14:49:40.514875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9adfba05249b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_cafe_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_cafe_id'), ['target_cafe_id'], unique=False)

    op.create_table('cafes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('auth_id', sa.String(), nullable=True),
    sa.Column('google_maps_link', sa.String(), nullable=True),
    sa.Column('reward_text', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), server_default='trial', nullable=False),
    sa.Column('subscription_plan', sa.String(), nullable=True),
    sa.Column('razorpay_customer_id', sa.String(), nullable=True),
    sa.Column('plan_expiry', sa.DateTime(), nullable=True),
    sa.Column('marketing_credits', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cafes_auth_id'), ['auth_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_cafes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cafes_slug'), ['slug'], unique=True)

    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='unread', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_messages_id'), ['id'], unique=False)

    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupons_cafe_id'), ['cafe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupons_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_coupons_customer_phone'), ['customer_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupons_id'), ['id'], unique=False)

    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cafe_id', sa.Integer(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('marketing_opt_in', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cafe_id'], ['cafes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedbacks_cafe_id'), ['cafe_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedbacks_customer_phone'), ['customer_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedbacks_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedbacks_id'))
        batch_op.drop_index(batch_op.f('ix_feedbacks_customer_phone'))
        batch_op.drop_index(batch_op.f('ix_feedbacks_cafe_id'))

    op.drop_table('feedbacks')
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupons_id'))
        batch_op.drop_index(batch_op.f('ix_coupons_customer_phone'))
        batch_op.drop_index(batch_op.f('ix_coupons_code'))
        batch_op.drop_index(batch_op.f('ix_coupons_cafe_id'))

    op.drop_table('coupons')
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_messages_id'))

    op.drop_table('contact_messages')
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cafes_slug'))
        batch_op.drop_index(batch_op.f('ix_cafes_id'))
        batch_op.drop_index(batch_op.f('ix_cafes_auth_id'))

    op.drop_table('cafes')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_cafe_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
