"""Fix hashed_password and add onboarding_completed

Revision ID: e80dbb2d20a1
Revises: 8d9968451bf5
Create Date: 2026-06-14 14:53:24.183258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e80dbb2d20a1'
down_revision: Union[str, Sequence[str], None] = '8d9968451bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_cafe_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_cafe_id'), ['target_cafe_id'], unique=False)

    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='unread', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_messages_id'), ['id'], unique=False)

    op.create_table('processed_webhooks',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('message_id')
    )
    with op.batch_alter_table('processed_webhooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_webhooks_message_id'), ['message_id'], unique=False)

    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('google_maps_link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('onboarding_completed', sa.Boolean(), server_default='0', nullable=False))
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_cafes_auth_id'), ['auth_id'], unique=True)

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupons_cafe_id'), ['cafe_id'], unique=False)
        batch_op.create_unique_constraint('uix_cafe_customer_coupon', ['cafe_id', 'customer_phone'])

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedbacks_cafe_id'), ['cafe_id'], unique=False)
        batch_op.create_unique_constraint('uix_cafe_customer_feedback', ['cafe_id', 'customer_phone'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_constraint('uix_cafe_customer_feedback', type_='unique')
        batch_op.drop_index(batch_op.f('ix_feedbacks_cafe_id'))

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_constraint('uix_cafe_customer_coupon', type_='unique')
        batch_op.drop_index(batch_op.f('ix_coupons_cafe_id'))

    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cafes_auth_id'))
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('onboarding_completed')
        batch_op.drop_column('google_maps_link')
        batch_op.drop_column('auth_id')

    with op.batch_alter_table('processed_webhooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_webhooks_message_id'))

    op.drop_table('processed_webhooks')
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_messages_id'))

    op.drop_table('contact_messages')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_cafe_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
