"""Add AuditLog and Cafe Subscriptions

Revision ID: f9f97cae53ab
Revises: 8c90a52a1950
Create Date: 2026-05-07 22:13:57.563587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f97cae53ab'
down_revision: Union[str, Sequence[str], None] = '8c90a52a1950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cafes', sa.Column('subscription_status', sa.String(), server_default='trial', nullable=False))
    op.add_column('cafes', sa.Column('subscription_plan', sa.String(), nullable=True))
    op.add_column('cafes', sa.Column('razorpay_customer_id', sa.String(), nullable=True))
    op.add_column('cafes', sa.Column('plan_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cafes', 'plan_expiry')
    op.drop_column('cafes', 'razorpay_customer_id')
    op.drop_column('cafes', 'subscription_plan')
    op.drop_column('cafes', 'subscription_status')
    # ### end Alembic commands ###
