-- 1. Align timezone columns
ALTER TABLE public.audit_logs ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC';
ALTER TABLE public.cafes ALTER COLUMN plan_expiry TYPE TIMESTAMP WITH TIME ZONE USING plan_expiry AT TIME ZONE 'UTC';
ALTER TABLE public.contact_messages ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC';
ALTER TABLE public.coupons ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC';
ALTER TABLE public.coupons ALTER COLUMN redeemed_at TYPE TIMESTAMP WITH TIME ZONE USING redeemed_at AT TIME ZONE 'UTC';
ALTER TABLE public.feedbacks ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC';
